// This file is generated by RustQ. Do not edit by hand.

fn worker_envelope<'a>(env: Env<'a>, token: Term<'a>, event: Term<'a>) -> Term<'a> {
    (atoms::laughter_native(), token, event).encode(env)
}
fn worker_element<'a>(
    env: Env<'a>,
    id: u64,
    tag: String,
    attributes: Vec<(String, String)>,
) -> Term<'a> {
    (atoms::element(), id, tag, attributes).encode(env)
}
fn worker_output<'a>(env: Env<'a>, id: u64, binary: Binary<'a>, finished: bool) -> Term<'a> {
    (atoms::output(), id, binary, finished).encode(env)
}
fn worker_error<'a>(env: Env<'a>, reason: Term<'a>) -> Term<'a> {
    (atoms::error(), reason).encode(env)
}
