// This file is generated by RustQ. Do not edit by hand.

#[derive(Clone, Debug, rustler::NifMap)]
pub struct Attribute {
    pub name: String,
    pub value: String,
}
pub type DynamicHandle = ResourceArc<DynamicSession>;
#[derive(Clone, Debug, rustler::NifTaggedEnum)]
pub enum Mutation {
    Remove,
    SetAttribute(Attribute),
    RemoveAttribute(String),
    PrependText(String),
    PrependHtml(String),
    AppendText(String),
    AppendHtml(String),
    BeforeText(String),
    BeforeHtml(String),
    AfterText(String),
    AfterHtml(String),
    ReplaceText(String),
    ReplaceHtml(String),
    SetInnerText(String),
    SetInnerHtml(String),
}
#[derive(Clone, Debug, rustler::NifMap)]
pub struct Rule {
    pub selector: String,
    pub mutation: Mutation,
}
pub type Session = ResourceArc<StreamSession>;
#[derive(Clone, Debug, rustler::NifMap)]
pub struct WorkerOptions {
    pub encoding: String,
    pub max_memory: usize,
    pub chunk_size: usize,
    pub max_output_bytes: usize,
    pub reply_timeout: usize,
}
#[rustler::nif]
fn rewrite_stats() -> (usize, usize, usize) {
    rewrite_stats_impl()
}
#[rustler::nif(schedule = "DirtyCpu")]
#[allow(unused_variables)]
fn rewrite_plan<'a>(
    env: Env<'a>,
    input: Binary<'a>,
    rules: Vec<Rule>,
    encoding: String,
    max_memory: usize,
) -> NifResult<(Atom, Binary<'a>)> {
    rewrite_plan_impl(env, input, rules, encoding, max_memory)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_stream_new(
    rules: Vec<Rule>,
    encoding: String,
    max_memory: usize,
    max_input_bytes: usize,
    max_output_bytes: usize,
) -> NifResult<(Atom, Session)> {
    stream_new_impl(
        rules,
        encoding,
        max_memory,
        max_input_bytes,
        max_output_bytes,
    )
}
#[rustler::nif(schedule = "DirtyCpu")]
#[allow(unused_variables)]
fn rewrite_stream_write<'a>(
    env: Env<'a>,
    session: Session,
    input: Binary<'a>,
) -> NifResult<(Atom, Binary<'a>)> {
    stream_write_impl(env, session, input)
}
#[rustler::nif(schedule = "DirtyCpu")]
#[allow(unused_variables)]
fn rewrite_stream_finish<'a>(env: Env<'a>, session: Session) -> NifResult<(Atom, Binary<'a>)> {
    stream_finish_impl(env, session)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_stream_close(session: Session) -> Atom {
    stream_close_impl(session)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_dynamic_new<'a>(
    rules: Vec<Rule>,
    selector: String,
    options: WorkerOptions,
    pid: LocalPid,
    token: Term<'a>,
) -> NifResult<(Atom, DynamicHandle)> {
    dynamic_new_impl(rules, selector, options, pid, token)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_dynamic_write<'a>(
    session: DynamicHandle,
    id: u64,
    input: Binary<'a>,
) -> NifResult<Atom> {
    dynamic_write_impl(session, id, input)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_dynamic_finish(session: DynamicHandle, id: u64) -> NifResult<Atom> {
    dynamic_finish_impl(session, id)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_dynamic_reply(
    session: DynamicHandle,
    id: u64,
    mutations: Vec<Mutation>,
) -> NifResult<Atom> {
    dynamic_reply_impl(session, id, mutations)
}
#[rustler::nif(schedule = "DirtyCpu")]
fn rewrite_dynamic_close(session: DynamicHandle) -> Atom {
    dynamic_close_impl(session)
}
fn apply_content_mutation(element: &mut lol_html::send::Element, mutation: &Mutation) {
    match mutation {
        Mutation::PrependText(content) if !element.removed() => {
            element.prepend(content, ContentType::Text)
        }
        Mutation::PrependHtml(content) if !element.removed() => {
            element.prepend(content, ContentType::Html)
        }
        Mutation::AppendText(content) if !element.removed() => {
            element.append(content, ContentType::Text)
        }
        Mutation::AppendHtml(content) if !element.removed() => {
            element.append(content, ContentType::Html)
        }
        Mutation::BeforeText(content) => element.before(content, ContentType::Text),
        Mutation::BeforeHtml(content) => element.before(content, ContentType::Html),
        Mutation::AfterText(content) => element.after(content, ContentType::Text),
        Mutation::AfterHtml(content) => element.after(content, ContentType::Html),
        Mutation::ReplaceText(content) => element.replace(content, ContentType::Text),
        Mutation::ReplaceHtml(content) => element.replace(content, ContentType::Html),
        Mutation::SetInnerText(content) if !element.removed() => {
            element.set_inner_content(content, ContentType::Text)
        }
        Mutation::SetInnerHtml(content) if !element.removed() => {
            element.set_inner_content(content, ContentType::Html)
        }
        _ => {}
    }
}
#[rustler::resource_impl]
impl rustler::Resource for DynamicSession {}
#[rustler::resource_impl]
impl rustler::Resource for StreamSession {}
