defmodule Laughter.Codegen.Nif do
  @moduledoc false

  # Export policy only. RustQ reads argument names, types, lifetimes and Env
  # injection from the implementations; no second list of signatures/arities.
  @legacy_exports [
    {"native/laughter_nif/src/lib.rs", [:build, :filter, :document_text, :create, :parse, :done]},
    {"native/laughter_nif/src/rewriter.rs",
     [
       :rewriter_new,
       :rewriter_on_element,
       :rewriter_on_text,
       :rewriter_write,
       :rewriter_poll,
       :rewriter_respond,
       :rewriter_output
     ]}
  ]

  def functions do
    legacy =
      @legacy_exports
      |> Enum.map(fn {path, names} ->
        {path, Enum.map(names, &{&1, [impl: &1]})}
      end)
      |> RustQ.Rustler.Nif.functions_from_sources()

    generated =
      Laughter.Codegen.Rewrite.items()
      |> Enum.filter(fn
        %RustQ.Rust.AST.Function{attrs: attrs} ->
          Enum.any?(attrs, &match?(%RustQ.Rust.AST.Attribute{path: [:rustler, :nif]}, &1))

        _ ->
          false
      end)
      |> Enum.map(&{&1.name, &1})

    functions = Enum.sort_by(legacy ++ generated, fn {name, _} -> to_string(name) end)
    names = Enum.map(functions, fn {name, _} -> to_string(name) end)

    if length(names) != length(Enum.uniq(names)) do
      raise ArgumentError, "duplicate NIF exports in the native boundary"
    end

    functions
  end

  def stubs do
    "# Generated by RustQ. Do not edit by hand.\n" <>
      RustQ.Rustler.Nif.stubs_from_functions(functions(), Laughter.Nif.GeneratedStubs)
  end
end
