# Generated by RustQ. Do not edit by hand.
defmodule Laughter.Nif.GeneratedStubs do
  @moduledoc false
  defmacro __using__(_opts) do
    quote do
      def build do
        :erlang.nif_error(:nif_not_loaded)
      end

      def create(_builder, _encoding, _max_memory) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def document_text(_builder, _pid, _raw_text) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def done(_rewriter) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def filter(_builder, _pid, _selector, _send_text, _end_tag, _raw_text) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def parse(_rewriter, _data) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_dynamic_close(_session) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_dynamic_finish(_session, _id) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_dynamic_new(_rules, _selector, _options, _pid, _token) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_dynamic_reply(_session, _id, _mutations) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_dynamic_write(_session, _id, _input) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_plan(_input, _rules, _encoding, _max_memory) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_stats do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_stream_close(_session) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_stream_finish(_session) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_stream_new(_rules, _encoding, _max_memory, _max_input_bytes, _max_output_bytes) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewrite_stream_write(_session, _input) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_new(_encoding, _max_memory) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_on_element(_config, _selector) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_on_text(_config, _selector) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_output(_handle) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_poll(_handle) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_respond(_handle, _mutations) do
        :erlang.nif_error(:nif_not_loaded)
      end

      def rewriter_write(_config, _data) do
        :erlang.nif_error(:nif_not_loaded)
      end
    end
  end
end
